# Generated by Django 5.0 on 2025-05-26 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_servicetype_soldservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.item')),
                ('sold_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to='accounts.soldservice')),
            ],
        ),
    ]
