# Generated by Django 5.0 on 2025-05-26 05:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_solditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldservice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
